server:
  port: 9098

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enable: true
    lease:
      duration: 5

spring:
  application:
    name: employer-service



